// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppEigenSS.h"
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello(SEXP spmat);
RcppExport SEXP RcppEigenSS_rcpp_hello(SEXP spmatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type spmat(spmatSEXP );
        List __result = rcpp_hello(spmat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
